- block:

  ########
  # copy #
  ########
  # - name: copy dotfiles
  #   template:
  #     src: template{{ item }}
  #     dest: ~/{{ item }}
  #     force: yes
  #   with_items: '{{ dot_files }}'

  #################
  # symbolic link #
  #################
  - name: checkout dotfiles
    git:
      repo: git@github.com:yoshiyoshifujii/dotfiles.git
      dest: {{ environment.home }}/dotfiles
      key_file: {{ environment.home }}/.ssh/id_rsa_github.pub

  # - name: create symlinks
  #   file:
  #     src: ~/dotfiles/{{ item }}
  #     dest: ~/{{ item }}
  #     state: link
  #     force: yes
  #   with_items: '{{ dot_files }}'

  tags:
    - dotfiles
