- block:

  ########
  # copy #
  ########
  - name: copy dotfiles
    template:
      src: template{{ item }}
      dest: ~/{{ item }}
      force: yes
    with_items: '{{ dot_files }}'

  #################
  # symbolic link #
  #################
  # - name: checkout dotfiles
  #   git:
  #     repo: https://github.com/{your_repository}/dotfiles.git
  #     dest: ~/dotfiles

  # - name: create symlinks
  #   file:
  #     src: ~/dotfiles/{{ item }}
  #     dest: ~/{{ item }}
  #     state: link
  #     force: yes
  #   with_items: '{{ dot_files }}'

  tags:
    - dotfiles
