- block:

  - name: 'add git config global user.name'
    git_config:
      name: user.name
      scope: global
      value: '{{ git_user_name }}'

  - name: 'add git config global user.email'
    git_config:
      name: user.email
      scope: global
      value: '{{ git_user_email }}'

  - name: 'core.editor'
    git_config:
      name: core.editor
      scope: global
      value: 'vim -c "set fenc=utf-8"'

  - name: 'color.ui'
    git_config:
      name: color.ui
      scope: global
      value: 'true'

  tags:
    - git
